### ISSUE TITLE
node-pre-gyp error

### ISSUE THREAD

**Issue by suenot** [alexandesigner/lets#15]
I had this error:
```bash
➜  boilerplate git:(master) yarn install
yarn install v1.13.0
warning ../../../package.json: No license field
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning bcrypt@1.0.3: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt hashes
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[1/2] ⠄ bcrypt
error /Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@10.15.0 | darwin | x64
node-pre-gyp info check checked for "/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt/lib/binding/bcrypt_lib.node" (not found)
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.15.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.15.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
gypgyp  info it worked if it ends with ok
info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info gypusing node@10.15.0 | darwin | x64
 info using node-gyp@3.8.0
gyp info using node@10.15.0 | darwin | x64
gypgyp  infoinfo  okok

gyp info it worked if it ends with ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | darwin | x64
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | darwin | x64
gypgyp  infoinfo  spawnspawn /usr/bin/python
 /usr/bin/python
gypgyp  infoinfo  spawn argsspawn args [ '/Users/suenot/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
 [ '/Users/suenot/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gypgyp  infoinfo  spawn argsspawn args   'binding.gyp',
   'binding.gyp',
gypgyp  infoinfo  spawn argsspawn args   '-f',
   '-f',
gypgyp  infoinfo  spawn argsspawn args   'make',
   'make',
gypgyp  infoinfo  spawn args   '-I',
gyp spawn argsinfo spawn args   '/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt/build/config.gypi',
   '-I',
gyp info spawn args   '/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/suenot/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/suenot/.node-gyp/10.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/suenot/.node-gyp/10.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/suenot/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/suenot/.node-gyp/10.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn args   '-I',
gyp info spawn args   '/Users/suenot/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/suenot/.node-gyp/10.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/suenot/.node-gyp/10.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/suenot/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/suenot/.node-gyp/10.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gypgyp info ok
info ok
gypgyp info  it worked if it ends with ok
info it worked if it ends with ok
gyp infogyp using  node-gyp@3.8.0
info usinggyp  node-gyp@3.8.0
info using node@10.15.0 | darwin | x64
gyp info using node@10.15.0 | darwin | x64
gyp gypinfo spawn  make
info spawn make
gyp infogyp spawn args  [ 'BUILDTYPE=Release', '-C', 'build' ]
info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
rm: ./Release/.deps/Release/obj.target/bcrypt_lib/src/blowfish.o.d.raw: No such file or directory
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/suenot/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/suenot/.nvm/versions/node/v10.15.0/bin/node" "/Users/suenot/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/suenot/.nvm/versions/node/v10.15.0/bin/node /Users/suenot/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/suenot/work/temp/lets/boilerplate/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/Users/suenot/.nvm/versions/node/v10.15.0/bin/node" "/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/Users/suenot/.nvm/versions/node/v10.15.0/bin/node /Users/suenot/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt/lib/binding' (1)
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/bcrypt_node.cc:1:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/suenot/.node-gyp/10.15.0/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/suenot/.node-gyp/10.15.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/bcrypt_node.cc:1:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/suenot/.node-gyp/10.15.0/include/node/node.h:169:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/suenot/.node-gyp/10.15.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/bcrypt_node.cc:1:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/suenot/.node-gyp/10.15.0/include/node/node.h:162:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/suenot/.node-gyp/10.15.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/bcrypt_node.cc:1:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/suenot/.node-gyp/10.15.0/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/suenot/.node-gyp/10.15.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/suenot/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/suenot/.nvm/versions/node/v10.15.0/bin/node" "/Users/suenot/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /Users/suenot/work/temp/lets/boilerplate/node_modules/bcrypt
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by alexandesigner** [comment]
Thanks for your feedback and sorry for the delay
 
This problem was a recurring bug in meteor using a specific version of babel-runtime, in [this update - 1.0.9](https://github.com/alexandesigner/lets/pull/16) I fixed this bug, give it another chance and tell me if I can help with anything else.

_I will close the question, reopen if the problem persists_
